---
abstract: 'naive intelligence about a body of text'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-IQ
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::EN::Syllable: '0'
  Search::Tools: '1.000'
  Test::More: '0'
  Text::Aspell: '0'
  perl: '5.008003'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Text-IQ
  homepage: https://github.com/karpet/text-iq-perl
  license: http://dev.perl.org/licenses/
version: '0.002'
